name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"

      - name: install dependencies
        run: npm i
      
      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      # Make directory to upload the test results
      - name: Make Directory for results and launch local server
        run: npm run tern-on-api & mkdir -p testResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run store.collection.json -e StoreEnv.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/index.html
      - name: Upload artifact report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: ./testResults 
      - name: Deploy to pages
          if: always()
          uses: peaceiris/actions-gh-pages@v3.7.3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: testResults/ 